### ISSUE TITLE
listen EACCES: permission denied 0.0.0.0:4200

### ISSUE THREAD

**Issue by marcelo-maciel** [sergiovision/FinCore#2]
Hi Sergio!

In FinCore\ClientApp folder, I run "npm start" with admin previlegies, but the following error occurred:

LOG:
[error] Error: listen EACCES: permission denied 0.0.0.0:4200
    at Server.setupListenHandle [as _listen2] (net.js:1299:21)
    at listenInCluster (net.js:1364:12)
    at doListen (net.js:1501:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

If I try a "npm install" again in "ClientApp" folder, then this other error occurs:

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by marcelo-maciel** [comment]
I solved all my problems uncommenting all these lines in Startup.cs:

`       

                    spa.UseAngularCliServer(npmScript: "start");

                    spa.UseProxyToSpaDevelopmentServer(Configuration["DebugClientURL"]);
                    

                    spa.UseProxyToSpaDevelopmentServer(Configuration["ExternalClientURL"]);`
